change-id = 135832

[llvm]
ninja = false
link-shared = true
static-libstdcpp = false
use-libcxx = true
download-ci-llvm = false

[build]
build = 'x86_64-chimera-linux-musl'
host = ['x86_64-unknown-linux-musl']
target = ['x86_64-unknown-linux-musl']

cargo = '/usr/bin/cargo'
rustc = '/usr/bin/rustc'

docs = false

python = 'python'

locked-deps = true
vendor = true

extended = true

tools = ['cargo', 'rustfmt']

profiler = true

local-rebuild = false

[install]
prefix = '/usr'

[rust]
optimize = true
debug = false
backtrace-on-ice = true
codegen-units = 1
codegen-units-std = 1

debuginfo-level = 0
debuginfo-level-std = 0

lto = 'thin'

incremental = false

channel = 'beta'
description = 'musl.rs'

rpath = true

frame-pointers = true

deny-warnings = false

llvm-libunwind = 'system'

[dist]
vendor = false
src-tarball = true
compression-formats = ['xz']
compression-profile = 'best'

[target.x86_64-unknown-linux-musl]
cc = '/usr/bin/clang'
cxx = '/usr/bin/clang++'
ar = '/usr/bin/llvm-ar'
ranlib = '/usr/bin/llvm-ranlib'
linker = '/usr/bin/clang'
llvm-config = '/usr/bin/llvm-config'
crt-static = false
